-- 함수 이름 계층
-- OCS_OWNER 계정으로 실행한다. 210 까지 만든 뒤에 실행한다.
--
-- 개발자가 쿼리 안에서 패키지 이름 없이 FN_ENC_RRN(...) 처럼 짧은 함수 이름으로
-- 호출할 수 있도록, PKG_SECURE_API 의 함수마다 같은 동작의 단독 함수를 하나씩 둔다.
-- 단독 함수는 인자를 그대로 PKG_SECURE_API 에 넘기고 결과를 그대로 돌려줄 뿐이며,
-- 판단이나 통제를 새로 하지 않는다. 증표 검증, 복호화 자격, 마스킹, 감사는 모두
-- 아래 PKG_SECURE_API 가 그대로 적용한다.
--
-- 이름 규칙은 FN_ 뒤에 PKG_SECURE_API 의 함수 이름을 대문자로 붙인 것이다.
--   FN_ENC_RRN, FN_DEC_RRN, FN_MASK_RRN, FN_IDX_RRN, FN_PROTECT, FN_SHOW ...
--
-- 이 함수들은 OCS_OWNER 소유이므로 응용 스키마에서 이름만으로 쓰려면 실행 권한과
-- 시노님이 필요하다. 권한은 300_grants.sql 이 OCS_ROLE_APP 과 OCS_APP 에 주고,
-- 시노님은 04_admin/480_app_synonyms.sql 로 응용 스키마마다 만든다.
--
-- 호출마다 PL/SQL 호출이 한 번 더 들어가므로, 한 쿼리에서 많은 행에 부르는 곳은
-- 필요한 행만 대상으로 줄여야 한다. 이 점은 패키지를 직접 부를 때와 같다.

CREATE OR REPLACE FUNCTION FN_PROTECT(p_domain_code IN VARCHAR2, p_plain IN VARCHAR2) RETURN RAW IS
BEGIN
  RETURN PKG_SECURE_API.protect(p_domain_code, p_plain);
END FN_PROTECT;
/

CREATE OR REPLACE FUNCTION FN_REVEAL(p_domain_code IN VARCHAR2, p_cipher IN RAW) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.reveal(p_domain_code, p_cipher);
END FN_REVEAL;
/

CREATE OR REPLACE FUNCTION FN_MASKED(p_domain_code IN VARCHAR2, p_cipher IN RAW) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.masked(p_domain_code, p_cipher);
END FN_MASKED;
/

CREATE OR REPLACE FUNCTION FN_SHOW(p_domain_code IN VARCHAR2, p_cipher IN RAW) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.show(p_domain_code, p_cipher);
END FN_SHOW;
/

CREATE OR REPLACE FUNCTION FN_SEARCH_OF(p_domain_code IN VARCHAR2, p_plain IN VARCHAR2) RETURN RAW IS
BEGIN
  RETURN PKG_SECURE_API.search_of(p_domain_code, p_plain);
END FN_SEARCH_OF;
/

CREATE OR REPLACE FUNCTION FN_ALLOWED(p_domain_code IN VARCHAR2) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.allowed(p_domain_code);
END FN_ALLOWED;
/

CREATE OR REPLACE FUNCTION FN_ENC_RRN(p_rrn IN VARCHAR2) RETURN RAW IS
BEGIN
  RETURN PKG_SECURE_API.enc_rrn(p_rrn);
END FN_ENC_RRN;
/

CREATE OR REPLACE FUNCTION FN_DEC_RRN(p_cipher IN RAW) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.dec_rrn(p_cipher);
END FN_DEC_RRN;
/

CREATE OR REPLACE FUNCTION FN_MASK_RRN(p_cipher IN RAW) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.mask_rrn(p_cipher);
END FN_MASK_RRN;
/

CREATE OR REPLACE FUNCTION FN_IDX_RRN(p_rrn IN VARCHAR2) RETURN RAW IS
BEGIN
  RETURN PKG_SECURE_API.idx_rrn(p_rrn);
END FN_IDX_RRN;
/

CREATE OR REPLACE FUNCTION FN_ENC_ACCOUNT(p_account IN VARCHAR2) RETURN RAW IS
BEGIN
  RETURN PKG_SECURE_API.enc_account(p_account);
END FN_ENC_ACCOUNT;
/

CREATE OR REPLACE FUNCTION FN_DEC_ACCOUNT(p_cipher IN RAW) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.dec_account(p_cipher);
END FN_DEC_ACCOUNT;
/

CREATE OR REPLACE FUNCTION FN_MASK_ACCOUNT(p_cipher IN RAW) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.mask_account(p_cipher);
END FN_MASK_ACCOUNT;
/

CREATE OR REPLACE FUNCTION FN_IDX_ACCOUNT(p_account IN VARCHAR2) RETURN RAW IS
BEGIN
  RETURN PKG_SECURE_API.idx_account(p_account);
END FN_IDX_ACCOUNT;
/

CREATE OR REPLACE FUNCTION FN_ENC_NAME(p_name IN VARCHAR2) RETURN RAW IS
BEGIN
  RETURN PKG_SECURE_API.enc_name(p_name);
END FN_ENC_NAME;
/

CREATE OR REPLACE FUNCTION FN_DEC_NAME(p_cipher IN RAW) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.dec_name(p_cipher);
END FN_DEC_NAME;
/

CREATE OR REPLACE FUNCTION FN_MASK_NAME(p_cipher IN RAW) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.mask_name(p_cipher);
END FN_MASK_NAME;
/

CREATE OR REPLACE FUNCTION FN_IDX_NAME(p_name IN VARCHAR2) RETURN RAW IS
BEGIN
  RETURN PKG_SECURE_API.idx_name(p_name);
END FN_IDX_NAME;
/

CREATE OR REPLACE FUNCTION FN_MAKE_PWD(p_password IN VARCHAR2) RETURN RAW IS
BEGIN
  RETURN PKG_SECURE_API.make_pwd(p_password);
END FN_MAKE_PWD;
/

CREATE OR REPLACE FUNCTION FN_VERIFY_PWD(p_password IN VARCHAR2, p_stored IN RAW) RETURN NUMBER IS
BEGIN
  RETURN PKG_SECURE_API.verify_pwd(p_password, p_stored);
END FN_VERIFY_PWD;
/

CREATE OR REPLACE FUNCTION FN_PWD_STALE(p_stored IN RAW) RETURN NUMBER IS
BEGIN
  RETURN PKG_SECURE_API.pwd_stale(p_stored);
END FN_PWD_STALE;
/

CREATE OR REPLACE FUNCTION FN_MAKE_PWD_STR(p_password IN VARCHAR2) RETURN VARCHAR2 IS
BEGIN
  RETURN PKG_SECURE_API.make_pwd_str(p_password);
END FN_MAKE_PWD_STR;
/

CREATE OR REPLACE FUNCTION FN_CHECK_PWD(p_password IN VARCHAR2, p_stored IN VARCHAR2) RETURN NUMBER IS
BEGIN
  RETURN PKG_SECURE_API.check_pwd(p_password, p_stored);
END FN_CHECK_PWD;
/

CREATE OR REPLACE FUNCTION FN_PWD_STATE(p_stored IN VARCHAR2) RETURN NUMBER IS
BEGIN
  RETURN PKG_SECURE_API.pwd_state(p_stored);
END FN_PWD_STATE;
/

CREATE OR REPLACE FUNCTION FN_READY RETURN NUMBER IS
BEGIN
  RETURN PKG_SECURE_API.ready;
END FN_READY;
/
